version: '3'

services:
  devbox:
    container_name: devbox
    image: wraithgar/devbox
    environment:
      - DISPLAY=host.docker.internal:0
      - LANG
    volumes:
      # Cached stuff (host is authoritative, rarely changes so delays don't matter)
      - /Users/wraithgar/.ssh:/home/gar/.ssh:cached
      # - /home/wraithgar/.gnupg:/home/gar/.gnupg:cached
      - /Users/wraithgar/.aws:/home/gar/.aws:cached
      - /Users/wraithgar/.npmrc:/home/gar/.npmrc:cached
      # Delegated stuff (container is authoritative, changes often so delays matter)
      - /Users/wraithgar/Development:/home/gar/Development:delegated
      - ./private/fish_history:/home/gar/.local/share/fish/fish_history:delegated
